"""create streams table

Revision ID: 1fedce92302b
Revises: 29b15ff4e35b
Create Date: 2020-09-21 21:00:05.304534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fedce92302b'
down_revision = '29b15ff4e35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_title', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('message_edited', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('vod_url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'channel_id', name='_message_channel_uc'),
    sa.UniqueConstraint('vod_url')
    )
    op.create_index(op.f('ix_stream_timestamp'), 'stream', ['timestamp'], unique=False)
    op.drop_column('user', 'thumbnail_url')
    op.drop_column('user', 'is_online')
    op.drop_column('user', 'stream_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stream_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stream_timestamp'), table_name='stream')
    op.drop_table('stream')
    # ### end Alembic commands ###
