"""create alerts table

Revision ID: 23825ddf6542
Revises: 1fedce92302b
Create Date: 2020-09-21 21:24:58.747642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23825ddf6542'
down_revision = '1fedce92302b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='_user_channel_uc')
    )
    op.create_table('online_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_title', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('message_edited', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('vod_url', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vod_url')
    )
    op.create_index(op.f('ix_online_alert_timestamp'), 'online_alert', ['timestamp'], unique=False)
    op.drop_index('ix_stream_timestamp', table_name='stream')
    op.drop_table('stream')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_edited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('vod_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='stream_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stream_pkey'),
    sa.UniqueConstraint('message_id', 'channel_id', name='_message_channel_uc'),
    sa.UniqueConstraint('vod_url', name='stream_vod_url_key')
    )
    op.create_index('ix_stream_timestamp', 'stream', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_online_alert_timestamp'), table_name='online_alert')
    op.drop_table('online_alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
